-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 14:56:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca` (
  `ID` INT NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Gerente_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Biblioteca_Funcionarios1`
    FOREIGN KEY (`Gerente_CPF`)
    REFERENCES `Funcionarios` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Biblioteca_Funcionarios1_idx` ON `Biblioteca` (`Gerente_CPF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Categoria` (
  `Sigla` CHAR(8) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Classifica` (
  `Livro_ISBN` VARCHAR(17) NOT NULL,
  `Categoria_Sigla` CHAR(8) NOT NULL,
  `Idade Indicativa` INT NOT NULL,
  PRIMARY KEY (`Livro_ISBN`, `Categoria_Sigla`),
  CONSTRAINT `fk_Livro_has_Categoria_Livro1`
    FOREIGN KEY (`Livro_ISBN`)
    REFERENCES `Livro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_Sigla`)
    REFERENCES `Categoria` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Livro_has_Categoria_Categoria1_idx` ON `Classifica` (`Categoria_Sigla` ASC) VISIBLE;

CREATE INDEX `fk_Livro_has_Categoria_Livro1_idx` ON `Classifica` (`Livro_ISBN` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editora` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Funcionarios` (
  `CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `Salario` FLOAT NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Biblioteca_ID` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_Funcionarios_Biblioteca1`
    FOREIGN KEY (`Biblioteca_ID`)
    REFERENCES `Biblioteca` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Funcionarios_Biblioteca1_idx` ON `Funcionarios` (`Biblioteca_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Livro` (
  `ISBN` VARCHAR(17) NOT NULL,
  `TItulo` VARCHAR(45) NOT NULL,
  `Data de Publicacao` DATE NOT NULL,
  `Autor` VARCHAR(45) NOT NULL,
  `Secao_ID` INT NOT NULL,
  `Usuario_CPF` VARCHAR(45) NULL,
  `Editora_ID` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `fk_Livro_Secao1`
    FOREIGN KEY (`Secao_ID`)
    REFERENCES `Secao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Usuario1`
    FOREIGN KEY (`Usuario_CPF`)
    REFERENCES `Usuario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Editora1`
    FOREIGN KEY (`Editora_ID`)
    REFERENCES `Editora` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Livro_Secao1_idx` ON `Livro` (`Secao_ID` ASC) VISIBLE;

CREATE INDEX `fk_Livro_Usuario1_idx` ON `Livro` (`Usuario_CPF` ASC) VISIBLE;

CREATE INDEX `fk_Livro_Editora1_idx` ON `Livro` (`Editora_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Secao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Secao` (
  `ID` INT NOT NULL,
  `Numero de Livros` INT NULL,
  `Biblioteca_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Secao_Biblioteca1`
    FOREIGN KEY (`Biblioteca_ID`)
    REFERENCES `Biblioteca` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Secao_Biblioteca1_idx` ON `Secao` (`Biblioteca_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Usuario` (
  `CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NULL,
  `Data de Nascimento` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
